POST http://localhost:3000/api/pageVisit/addPageVisit
Content-Type: application/json

{
    "pageVisit": 22
}

###
GET http://localhost:3000/api/pageVisit/getPageVisit

###
POST http://localhost:3000/api/chatBot/Gemini2.0Flash
Content-Type: application/json

{
    "prompt": "Hello"
}